export const browserCoreExamples = [
  "aren browser status",
  "aren browser start",
  "aren browser stop",
  "aren browser tabs",
  "aren browser open https://example.com",
  "aren browser focus abcd1234",
  "aren browser close abcd1234",
  "aren browser screenshot",
  "aren browser screenshot --full-page",
  "aren browser screenshot --ref 12",
  "aren browser snapshot",
  "aren browser snapshot --format aria --limit 200",
  "aren browser snapshot --efficient",
  "aren browser snapshot --labels",
];

export const browserActionExamples = [
  "aren browser navigate https://example.com",
  "aren browser resize 1280 720",
  "aren browser click 12 --double",
  'aren browser type 23 "hello" --submit',
  "aren browser press Enter",
  "aren browser hover 44",
  "aren browser drag 10 11",
  "aren browser select 9 OptionA OptionB",
  "aren browser upload /tmp/file.pdf",
  'aren browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "aren browser dialog --accept",
  'aren browser wait --text "Done"',
  "aren browser evaluate --fn '(el) => el.textContent' --ref 7",
  "aren browser console --level error",
  "aren browser pdf",
];
